### ISSUE TITLE
Can't login after deleting the .cargo directory

### ISSUE THREAD

**Issue by TheMG95** [apognu/tuigreet#114]
While trying to move the `.cargo` directory, I deleted it and rebooted my machine. After logging back in, the screen flashed with an error similar to `Directory not found: /home/user/.cargo/env/` for a second and then returned me to the login screen. I changed the command that's executed, but it seems to fail before the command is executed, so I figured the problem was caused by tuigreet. I know that it is my dumbness that caused this but is there a way to fix this easily or do I need to boot into another OS and create the `.cargo/env` directory?

I apologize in advance if this has nothing to do with tuigreet and is caused by another program.

**Comment by apognu** [comment]
Hey, I am not sure this is related to `tuigreet`, we do not have dependency with anything in your user directory (because when `tuigreet` is running, the user is not logged in yet, so we cannot read it).

My guess would be that either the session command, or something that is run after had that dependency.

Other than that, I don't think you need to boot another OS to try and fix it, either log into another Linux TTY to get a shell and fix your environment, or even log into `tuigreet` but setting a shell as its command with `F2` should at least allow you to try and fix the issue.
