### ISSUE TITLE
Provided session not selected by default

### ISSUE THREAD

**Issue by JManch** [apognu/tuigreet#141]
**Describe the bug**
In the previous version, providing a single session with `--sessions` would select that session by default. Now, the CMD defaults to `-` and I have to manually select the session every login.

**To Reproduce**
Launch tuigreet with `tuigreet --sessions <session_dir>`

**Expected behavior**
The provided session should be selected by default

**System information:**
 - Distribution: NixOS
 - `greetd` version: `0.9.0`
 - `tuigreet` version: `0.9.0`

**Comment by apognu** [comment]
What do you mean by "providing a single session" ? Providing a directory containing a single desktop file?

**Comment by bertini97** [comment]
I would like to add that the same behavior happens when `--session` is not specified. No session is selected by default, and when you try to log in, it just doesn't. Took me a while to figure this out, it felt like a bug.

It would be cool if tuigreet had a way to pick a default session, as most login managers do. Especially when there is only one desktop file.

**Comment by apognu** [comment]
This should be fixed on the `dev/default-session` branch.

I will probably merge this and #140 when I can properly test them (I lost access to my main development computer, so it is a bit harder right now).

**Comment by apognu** [comment]
This is now available in the 0.9.1 version of `tuigreet`.

**Comment by andyrtr** [comment]
The new release seems to break --remember-user-session for me here. The last successful session isn't remembered anymore. Is this now intentional?
