### ISSUE TITLE
formatting issue

### ISSUE THREAD

**Issue by 909oce** [apognu/tuigreet#152]
theres a weird box and random x that started yesterday.

using flags --time --asterisks --remember, but it happens without them too

![PXL_20240815_205002382.jpg](https://github.com/user-attachments/assets/31547715-c9ca-4753-9f66-5997e49c7cf5)

**Comment by apognu** [comment]
I will have a look. The weird box before "archlinux" rings a bell, so it might be easy to reproduce, hopefully. I will update this when I get access to a computer.

Thanks for reporting.

**Comment by apognu** [comment]
The weird character before the hostname seems to be due to the localization system adding (supposedly) invisible control characters around it, and ratatui 0.27 apparently rendering it in the Linux console. As a temporary measure, I now remove them before rendering them, which should fix this issue.

I was not able to reproduce the `x` issue yet, though.

**Comment by 909oce** [comment]
all fixed now. the x seems to be gone aswell. thank you for the quick update!
