### ISSUE TITLE
/var/cache/tuigreet did not exist

### ISSUE THREAD

**Issue by iv4nux** [apognu/tuigreet#33]
Hello,

On Gentoo, I had to create /var/cache/tuigreet (ownership greetd:greetd) to have the "--remember" and "--remember-session" parameter work normally.

It may be the way my system is setup and not a tuigreet bug in itself, but that information may come in handy for others.

Thanks for the great application - Much useful to start Wayland without xorg! :-)

**Comment by IchikaOmamori** [comment]
I encounter the same problem, thanks for sharing the solution.

**Comment by apognu** [comment]
I'll make sure `tuigreet` creates the directory if missing when I get back from vacation.

**Comment by apognu** [comment]
I was a bit quick in responding to this. The directory should be created when `tuigreet` is installed, by the package manager / installation script, since `/var/cache` cannot be written to by `greetd`.

The Gentoo port is not officially maintained by me, you should therefore contact the package maintainer (@epsilon-0).

**Comment by apognu** [comment]
I'll close this due to inactivity. It is my belief this should be handled by the installation scripts / package manager, and not by us.

**Comment by lucilanga** [comment]
On the other hand, it would be nice to mention this in the readme file. I had to dig through github closed issues to find why --remember stuff wasn't working.
