### ISSUE TITLE
Make the --time flag configurable

### ISSUE THREAD

**Issue by kugelblitz2** [apognu/tuigreet#54]
It would be nice to be able to configure the layout of the time displayed by --time using a string of format codes

https://www.programiz.com/python-programming/datetime/strftime

**Comment by apognu** [comment]
This is implemented in a separate branch for now, because I am not fully convinced preventing launch on invalid format strings is such a good idea. But the alternative is to ignore the option in that case, which is not perfect either.

I'll think about it, but it is funtionally done and will be included in the next version.

**Comment by apognu** [comment]
This is now available on `master`.
