### ISSUE TITLE
Feature Suggestion: Command Keybinding Configuration

### ISSUE THREAD

**Issue by dsh0005** [apognu/tuigreet#83]
I'm on Gentoo, using version 0.8.0-r1. It seems to work well, except I physically don't have a F12 key on my machine, which was originally a Chromebook, so I can't use the power options.

This isn't an enormous deal for me, since I can just hit the power key, but it does strike me that it might be nice to rebind which keys are used for which commands.

**Comment by apognu** [comment]
Rebinding actions to other F keys is now supported on the main branch (sorry about the delay :eyes:).

**Comment by Timoyoungster** [comment]
Hi,
could we reopen this to expand the suggestion to include full custom bindings?
I am using a very minimalistic custom keyboard and since I typically don't need them, I have the F-keys in a layer that's slightly more cumbersome to get into than others.
That's why I try to avoid the F-keys as much as possible and why I would really welcome having the option to rebind the various actions to other keys (e.g. control + ...).

If that is something that would be considered for merging, I'd also be happy to write up a pr for this.
